/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pkg2232_finalproject;

/**
 *
 * @author zeynepakhan
 */
public class CommentEditorFrame extends javax.swing.JFrame {

    /**
     * Creates new form CommentEditorFrame
     */
    private int currentMovieId;
    public CommentEditorFrame(int movieId) {
        initComponents();
        this.setResizable(false);
    this.currentMovieId = movieId;
    loadComment();
    }
private void loadComment() {
    try {
        java.sql.Connection conn = DBConnection.getConnection();
        
        String sql = "SELECT Title, Comments FROM Movie WHERE MovieID = ?";
        java.sql.PreparedStatement pst = conn.prepareStatement(sql);
        pst.setInt(1, currentMovieId);
        java.sql.ResultSet rs = pst.executeQuery();
        
        if (rs.next()) {
            lblMovieTitle.setText(rs.getString("Title")); 
            txtComment.setText(rs.getString("Comments")); 
        }
        conn.close();
    } catch (Exception e) { 
        e.printStackTrace(); 
    }
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtComment = new javax.swing.JTextArea();
        btnDeleteComment = new javax.swing.JButton();
        lblMovieTitle = new javax.swing.JLabel();
        btnSaveComment = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setText("Movie Title:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(76, 91, -1, -1));

        txtComment.setColumns(20);
        txtComment.setRows(5);
        jScrollPane1.setViewportView(txtComment);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(67, 152, -1, -1));

        btnDeleteComment.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnDeleteComment.setText("Delete/Clear Comment");
        btnDeleteComment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteCommentActionPerformed(evt);
            }
        });
        getContentPane().add(btnDeleteComment, new org.netbeans.lib.awtextra.AbsoluteConstraints(67, 284, -1, -1));

        lblMovieTitle.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        getContentPane().add(lblMovieTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 90, 250, 20));

        btnSaveComment.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnSaveComment.setText("Save Changes");
        btnSaveComment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveCommentActionPerformed(evt);
            }
        });
        getContentPane().add(btnSaveComment, new org.netbeans.lib.awtextra.AbsoluteConstraints(67, 349, -1, -1));

        jLabel2.setFont(new java.awt.Font("Copperplate", 1, 24)); // NOI18N
        jLabel2.setText("MANAGE COMMENTS");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 20, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pkg2232_finalproject/images/c4f030132cc9da7fcd537d4d722e5d07.png"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 710, 440));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDeleteCommentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteCommentActionPerformed
       txtComment.setText("");
    javax.swing.JOptionPane.showMessageDialog(this, "Comment cleared. Click Save to confirm.");
    }//GEN-LAST:event_btnDeleteCommentActionPerformed

    private void btnSaveCommentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveCommentActionPerformed
       
       try {
        java.sql.Connection conn = DBConnection.getConnection();
        String sql = "UPDATE Movie SET Comments = ? WHERE MovieID = ?";
        java.sql.PreparedStatement pst = conn.prepareStatement(sql);
        pst.setString(1, txtComment.getText());
        pst.setInt(2, currentMovieId);
        pst.executeUpdate();
        
        javax.swing.JOptionPane.showMessageDialog(this, "Comment updated/moderated!");
        this.dispose(); 
        conn.close();
    } catch (Exception e) { e.printStackTrace(); }
    }//GEN-LAST:event_btnSaveCommentActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CommentEditorFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CommentEditorFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CommentEditorFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CommentEditorFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CommentEditorFrame(0).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDeleteComment;
    private javax.swing.JButton btnSaveComment;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblMovieTitle;
    private javax.swing.JTextArea txtComment;
    // End of variables declaration//GEN-END:variables
}
