/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pkg2232_finalproject;

/**
 *
 * @author zeynepakhan
 */
public class MovieDetailsFrame extends javax.swing.JFrame {

    /**
     * Creates new form MovieDetailsFrame
     */
    private int mid;
    private int userType;
    public MovieDetailsFrame(int movieId, int uType) {
        initComponents(); 
        this.setResizable(false);
        this.mid = movieId;
        this.userType = uType;
        loadMovieDetails();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        lblTitle = new javax.swing.JLabel();
        lblYear = new javax.swing.JLabel();
        lblLanguage = new javax.swing.JLabel();
        lblCountry = new javax.swing.JLabel();
        lblGenre = new javax.swing.JLabel();
        lblDirector = new javax.swing.JLabel();
        lblLeadingActor = new javax.swing.JLabel();
        lblSupportingActor = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAbout = new javax.swing.JTextArea();
        jLabel8 = new javax.swing.JLabel();
        lblRating = new javax.swing.JLabel();
        lblRestriction = new javax.swing.JLabel();
        lblPoster = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTitle.setFont(new java.awt.Font("Copperplate", 1, 24)); // NOI18N
        getContentPane().add(lblTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 20, 440, 21));

        lblYear.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        getContentPane().add(lblYear, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, 241, 26));

        lblLanguage.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        getContentPane().add(lblLanguage, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 290, 244, 30));

        lblCountry.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        getContentPane().add(lblCountry, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, 272, 29));

        lblGenre.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        getContentPane().add(lblGenre, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 110, 242, 24));

        lblDirector.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        getContentPane().add(lblDirector, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 200, 427, 21));

        lblLeadingActor.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        getContentPane().add(lblLeadingActor, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 390, 290, 29));

        lblSupportingActor.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        getContentPane().add(lblSupportingActor, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 480, 305, 29));

        txtAbout.setEditable(false);
        txtAbout.setColumns(20);
        txtAbout.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtAbout.setLineWrap(true);
        txtAbout.setRows(5);
        txtAbout.setWrapStyleWord(true);
        jScrollPane1.setViewportView(txtAbout);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 600, -1, -1));

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel8.setText("About:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 630, -1, -1));

        lblRating.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        getContentPane().add(lblRating, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 300, 199, -1));

        lblRestriction.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        getContentPane().add(lblRestriction, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 390, 199, -1));
        getContentPane().add(lblPoster, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 460, 271, 249));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pkg2232_finalproject/images/c4f030132cc9da7fcd537d4d722e5d07.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 270, 730, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pkg2232_finalproject/images/c4f030132cc9da7fcd537d4d722e5d07 kopyası.png"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 730, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pkg2232_finalproject/images/c4f030132cc9da7fcd537d4d722e5d07 kopyası.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, -1, 240));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    private void loadMovieDetails() {
    
    try {
        java.sql.Connection conn = DBConnection.getConnection();
        
        String sql = "SELECT m.*, d.FirstName AS DirFN, d.LastName AS DirLN, " +
                     "la.FirstName AS LeadFN, la.LastName AS LeadLN, " +
                     "sa.FirstName AS SuppFN, sa.LastName AS SuppLN " +
                     "FROM Movie m " +
                     "LEFT JOIN Person d ON m.DirectorId = d.PersonID " +
                     "LEFT JOIN Person la ON m.LeadingActorId = la.PersonID " +
                     "LEFT JOIN Person sa ON m.SupportingActorId = sa.PersonID " +
                     "WHERE m.MovieID = ?";
        
        java.sql.PreparedStatement pst = conn.prepareStatement(sql);
        pst.setInt(1, mid);
        java.sql.ResultSet rs = pst.executeQuery();

        if (rs.next()) {
            
            boolean isRestricted = rs.getBoolean("ParentalRestriction");
            if (userType == 2 && isRestricted) {
                javax.swing.JOptionPane.showMessageDialog(this, "Access Denied: This movie is restricted for children!");
                this.dispose();
                return;
            }

            
            lblTitle.setText(rs.getString("Title"));
            lblYear.setText("Release Year: " + rs.getInt("ReleaseYear"));
            lblLanguage.setText("Language: " + rs.getString("Language"));
            lblCountry.setText("Country: " + rs.getString("CountryOfOrigin"));
            lblGenre.setText("Genre: " + rs.getString("Genre"));
            
           
            String director = (rs.getString("DirFN") != null) ? rs.getString("DirFN") + " " + rs.getString("DirLN") : "Unknown";
            lblDirector.setText("Director: " + director);
            
            String leading = (rs.getString("LeadFN") != null) ? rs.getString("LeadFN") + " " + rs.getString("LeadLN") : "N/A";
            lblLeadingActor.setText("Leading Actor: " + leading);
            
            String supporting = (rs.getString("SuppFN") != null) ? rs.getString("SuppFN") + " " + rs.getString("SuppLN") : "N/A";
            lblSupportingActor.setText("Supporting Actor: " + supporting);
            
           
            txtAbout.setText(rs.getString("About"));
            lblRating.setText("Family Rating: " + rs.getInt("Rating") + "/10");
            lblRestriction.setText("Restricted: " + (isRestricted ? "Yes" : "No"));

            
            try {
                String posterPath = rs.getString("Poster"); 
                if (posterPath != null && !posterPath.isEmpty()) {
                 
                    String resourcePath = posterPath.replace("src", ""); 
                    java.net.URL imgURL = getClass().getResource(resourcePath);
                    
                    if (imgURL != null) {
                        java.util.logging.Logger.getLogger(MovieDetailsFrame.class.getName()).log(java.util.logging.Level.INFO, "Loading poster: {0}", resourcePath);
                        javax.swing.ImageIcon imageIcon = new javax.swing.ImageIcon(imgURL);
                        java.awt.Image image = imageIcon.getImage();
                        
                        java.awt.Image scaledImg = image.getScaledInstance(lblPoster.getWidth(), lblPoster.getHeight(), java.awt.Image.SCALE_SMOOTH);
                        lblPoster.setIcon(new javax.swing.ImageIcon(scaledImg));
                        lblPoster.setText(""); 
                    } else {
                        lblPoster.setText("Poster not found");
                        System.err.println("Poster path invalid: " + resourcePath);
                    }
                }
            } catch (Exception imgEx) {
                System.err.println("Poster loading error: " + imgEx.getMessage());
                lblPoster.setText("Image Error");
            }
        }
        conn.close();
    } catch (Exception e) {
        javax.swing.JOptionPane.showMessageDialog(this, "Database Error: " + e.getMessage());
        e.printStackTrace();
    }
}
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MovieDetailsFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MovieDetailsFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MovieDetailsFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MovieDetailsFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MovieDetailsFrame(0,0).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCountry;
    private javax.swing.JLabel lblDirector;
    private javax.swing.JLabel lblGenre;
    private javax.swing.JLabel lblLanguage;
    private javax.swing.JLabel lblLeadingActor;
    private javax.swing.JLabel lblPoster;
    private javax.swing.JLabel lblRating;
    private javax.swing.JLabel lblRestriction;
    private javax.swing.JLabel lblSupportingActor;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblYear;
    private javax.swing.JTextArea txtAbout;
    // End of variables declaration//GEN-END:variables
}
