/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pkg2232_finalproject;

/**
 *
 * @author zeynepakhan
 */
public class RatingViewFrame extends javax.swing.JFrame {

    /**
     * Creates new form RatingViewFrame
     */
   private int mid;

public RatingViewFrame(int movieId) {
    initComponents();
    this.setResizable(false);
    this.mid = movieId;
    loadData();
}
private void loadData() {
    try {
        java.sql.Connection conn = DBConnection.getConnection();
        
        String movieSql = "SELECT Title, Rating FROM Movie WHERE MovieID = ?";
        java.sql.PreparedStatement pst1 = conn.prepareStatement(movieSql);
        pst1.setInt(1, mid);
        java.sql.ResultSet rs1 = pst1.executeQuery();
        
        if(rs1.next()) {
            lblMovieTitle.setText(rs1.getString("Title"));
            int mainRating = rs1.getInt("Rating");
            lblRating.setText(mainRating + " / 10"); 
        }

        String commentSql = "SELECT UserName, UserComment, UserRating FROM UserComments WHERE MovieID = ?";
        java.sql.PreparedStatement pst2 = conn.prepareStatement(commentSql);
        pst2.setInt(1, mid);
        java.sql.ResultSet rs2 = pst2.executeQuery();
        
        txtComments.setText(""); 
        while(rs2.next()) {
            String uName = rs2.getString("UserName");
            String uComm = rs2.getString("UserComment");
            int uRate = rs2.getInt("UserRating"); 
            
            txtComments.append("User: " + uName + (uRate > 0 ? " (" + uRate + "/10)" : "") + "\n");
            txtComments.append("Comment: " + uComm + "\n");
            txtComments.append("--------------------------------------------------\n");
        }
        
        conn.close();
    } catch (Exception e) { 
        e.printStackTrace(); 
    }

}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lblMovieTitle = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblRating = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtComments = new javax.swing.JTextArea();
        JButton = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setText("Movie Title:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(65, 114, -1, -1));

        lblMovieTitle.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        getContentPane().add(lblMovieTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 120, 280, 30));

        jLabel2.setFont(new java.awt.Font("Copperplate", 1, 24)); // NOI18N
        jLabel2.setText("VIEW RATINGS");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 30, -1, -1));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel3.setText("Rating:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(65, 186, -1, -1));

        lblRating.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        getContentPane().add(lblRating, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 190, 220, 17));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel4.setText("Comments:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(65, 274, -1, -1));

        txtComments.setEditable(false);
        txtComments.setColumns(20);
        txtComments.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        txtComments.setRows(5);
        jScrollPane1.setViewportView(txtComments);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 260, -1, -1));

        JButton.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        JButton.setText("Close");
        JButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JButtonActionPerformed(evt);
            }
        });
        getContentPane().add(JButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 390, -1, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pkg2232_finalproject/images/c4f030132cc9da7fcd537d4d722e5d07.png"))); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(-100, 0, 680, 460));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JButtonActionPerformed
        this.dispose();
    }//GEN-LAST:event_JButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RatingViewFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RatingViewFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RatingViewFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RatingViewFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RatingViewFrame(0).setVisible(true);
            }
        });
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblMovieTitle;
    private javax.swing.JLabel lblRating;
    private javax.swing.JTextArea txtComments;
    // End of variables declaration//GEN-END:variables
}
