/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pkg2232_finalproject;

/**
 *
 * @author zeynepakhan
 */
public class Type1MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form Type1MainFrame
     */
    public Type1MainFrame() {
        initComponents();
        this.setResizable(false);
        updateMovieTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblMovies = new javax.swing.JTable();
        btnConnect = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnRefresh = new javax.swing.JButton();
        btnAnalytics = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        btnToggleRestriction = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        btnManageUsers = new javax.swing.JButton();
        txtSearch = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        btnViewRating = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(2, 0), new java.awt.Dimension(2, 0), new java.awt.Dimension(2, 32767));
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblMovies.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblMovies);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 60, 783, 220));

        btnConnect.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        btnConnect.setText("Add New Movie");
        btnConnect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConnectActionPerformed(evt);
            }
        });
        getContentPane().add(btnConnect, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 540, -1, -1));

        btnEdit.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        btnEdit.setText("Edit Selected Movie");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });
        getContentPane().add(btnEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 540, -1, -1));

        btnDelete.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        btnDelete.setText("Delete Selected Movie");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        getContentPane().add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 540, -1, -1));

        btnRefresh.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        btnRefresh.setText("Refresh List");
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });
        getContentPane().add(btnRefresh, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 380, -1, -1));

        btnAnalytics.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        btnAnalytics.setText("View Family Analytics");
        btnAnalytics.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnalyticsActionPerformed(evt);
            }
        });
        getContentPane().add(btnAnalytics, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 320, -1, -1));

        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        jButton1.setText("Moderate Comment");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 320, -1, -1));

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel3.setText("Search Movie:");
        jLabel3.setOpaque(true);
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 480, -1, -1));

        btnToggleRestriction.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        btnToggleRestriction.setText("Change Age Rule");
        btnToggleRestriction.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnToggleRestrictionActionPerformed(evt);
            }
        });
        getContentPane().add(btnToggleRestriction, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 320, -1, -1));

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Copperplate", 3, 18)); // NOI18N
        jLabel4.setText("Manage Movies");
        jLabel4.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel4.setOpaque(true);
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 440, -1, -1));

        btnManageUsers.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        btnManageUsers.setText("Manage User Accounts");
        btnManageUsers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageUsersActionPerformed(evt);
            }
        });
        getContentPane().add(btnManageUsers, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, -1, -1));

        txtSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSearchActionPerformed(evt);
            }
        });
        txtSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSearchKeyReleased(evt);
            }
        });
        getContentPane().add(txtSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 480, 150, -1));

        jButton2.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        jButton2.setText("Browse");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 480, -1, -1));

        btnViewRating.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        btnViewRating.setText("View Family Rating");
        btnViewRating.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewRatingActionPerformed(evt);
            }
        });
        getContentPane().add(btnViewRating, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 380, -1, -1));

        btnLogout.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        btnLogout.setText("Logout");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });
        getContentPane().add(btnLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 480, -1, -1));

        filler1.setBackground(new java.awt.Color(30, 145, 145));
        filler1.setOpaque(true);
        getContentPane().add(filler1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 420, 800, 10));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Copperplate", 1, 24)); // NOI18N
        jLabel1.setText("Admin Dashboard - Movie Management");
        jLabel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel1.setOpaque(true);
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(156, 16, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pkg2232_finalproject/images/b99c237504dd5ae691d5587f30e3657a.png"))); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 820, 590));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        int selectedRow = tblMovies.getSelectedRow();
    if (selectedRow != -1) {
        int id = (int) tblMovies.getValueAt(selectedRow, 0); 
        int confirm = javax.swing.JOptionPane.showConfirmDialog(this, "Are you sure you want to delete this movie?", "Delete", javax.swing.JOptionPane.YES_NO_OPTION);
        
        if (confirm == javax.swing.JOptionPane.YES_OPTION) {
            try {
                java.sql.Connection conn = DBConnection.getConnection();
                String sql = "DELETE FROM Movie WHERE MovieID = ?";
                java.sql.PreparedStatement pst = conn.prepareStatement(sql);
                pst.setInt(1, id);
                pst.executeUpdate();
                conn.close();
                updateMovieTable(); 
            } catch (Exception e) {
                javax.swing.JOptionPane.showMessageDialog(this, "Delete error: " + e.getMessage());
            }
        }
    } else {
        javax.swing.JOptionPane.showMessageDialog(this, "Please select a movie to delete!");
    }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
     
    int selectedRow = tblMovies.getSelectedRow();
    
    if (selectedRow != -1) {
        try {
          
            int movieId = Integer.parseInt(tblMovies.getValueAt(selectedRow, 0).toString());
            
            AddMovieFrame editFrame = new AddMovieFrame(movieId); 
            editFrame.setVisible(true);
            
            
        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
        }
    } else {
        javax.swing.JOptionPane.showMessageDialog(this, "Please select a movie from the table to edit!");
    }
    }//GEN-LAST:event_btnEditActionPerformed

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
       updateMovieTable();
    }//GEN-LAST:event_btnRefreshActionPerformed

    private void btnAnalyticsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnalyticsActionPerformed
        try {
        java.sql.Connection conn = DBConnection.getConnection();
        java.sql.Statement st = conn.createStatement();

        java.sql.ResultSet rsAvg = st.executeQuery("SELECT AVG(Rating) FROM Movie");
        double avg = 0;
        if (rsAvg.next()) {
            avg = rsAvg.getDouble(1);
        }

        
        java.sql.ResultSet rsMost = st.executeQuery("SELECT Title FROM Movie WHERE Watched = 1 ORDER BY Rating DESC LIMIT 1");
        String mostWatched = "No movies watched yet.";
        if (rsMost.next()) {
            mostWatched = rsMost.getString("Title");
        }

        javax.swing.JOptionPane.showMessageDialog(this, 
            "--- Family Movie Analytics ---\n" +
            "Average Rating: " + String.format("%.2f", avg) + "\n" +
            "Featured Watched Movie: " + mostWatched);

        conn.close();
    } catch (Exception e) {
        javax.swing.JOptionPane.showMessageDialog(this, "Analytics Error: " + e.getMessage());
    }
    }//GEN-LAST:event_btnAnalyticsActionPerformed

    private void btnConnectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConnectActionPerformed
      AddMovieFrame addFrame = new AddMovieFrame();
    addFrame.setVisible(true);
    }//GEN-LAST:event_btnConnectActionPerformed

    private void btnToggleRestrictionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnToggleRestrictionActionPerformed
       int selectedRow = tblMovies.getSelectedRow(); 
    
    if (selectedRow != -1) {
        int movieId = (int) tblMovies.getValueAt(selectedRow, 0); 
        
        try {
            java.sql.Connection conn = DBConnection.getConnection();
            
            String sql = "UPDATE Movie SET ParentalRestriction = NOT ParentalRestriction WHERE MovieID = ?";
            
            java.sql.PreparedStatement pst = conn.prepareStatement(sql);
            pst.setInt(1, movieId);
            
            int result = pst.executeUpdate();
            if (result > 0) {
                javax.swing.JOptionPane.showMessageDialog(this, "Viewing rule updated successfully!");
                updateMovieTable(); 
            }
            conn.close();
        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Update Error: " + e.getMessage());
        }
    } else {
        javax.swing.JOptionPane.showMessageDialog(this, "Please select a movie from the table first!");
    }
    }//GEN-LAST:event_btnToggleRestrictionActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       int selectedRow = tblMovies.getSelectedRow();
    if (selectedRow != -1) {
       
        int movieId = (int) tblMovies.getValueAt(selectedRow, 0);
       
        CommentEditorFrame editor = new CommentEditorFrame(movieId);
        editor.setVisible(true);
    } else {
        javax.swing.JOptionPane.showMessageDialog(this, "Please select a movie first!");
    }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtSearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchKeyReleased
      String searchKey = txtSearch.getText();
    updateMovieTableWithSearch(searchKey);
    }//GEN-LAST:event_txtSearchKeyReleased

    private void btnViewRatingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewRatingActionPerformed
        int selectedRow = tblMovies.getSelectedRow();
    if (selectedRow != -1) {
        int movieId = (int) tblMovies.getValueAt(selectedRow, 0);
        new RatingViewFrame(movieId).setVisible(true);
    } else {
        javax.swing.JOptionPane.showMessageDialog(this, "Select a movie first!");
    }
    }//GEN-LAST:event_btnViewRatingActionPerformed

    private void txtSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSearchActionPerformed

    private void btnManageUsersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageUsersActionPerformed
        ManageUsersFrame manageFrame = new ManageUsersFrame();
    manageFrame.setVisible(true);
    }//GEN-LAST:event_btnManageUsersActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        int selectedRow = tblMovies.getSelectedRow();
     if (selectedRow != -1) {
    int id = Integer.parseInt(tblMovies.getValueAt(selectedRow, 0).toString());
    
    MovieDetailsFrame df = new MovieDetailsFrame(id, 1); 
    df.setVisible(true);
}
    }//GEN-LAST:event_jButton2ActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        this.dispose(); 
    
    new LoginFrame().setVisible(true);
    }//GEN-LAST:event_btnLogoutActionPerformed

    
    public void updateMovieTableWithSearch(String key) {
       String[] columnNames = {"ID", "Title", "Year", "Genre", "Director", "Rating", "Restriction"};
    javax.swing.table.DefaultTableModel model = new javax.swing.table.DefaultTableModel(columnNames, 0);
    
    try {
        java.sql.Connection conn = DBConnection.getConnection();
    
        String sql = "SELECT m.MovieID, m.Title, m.ReleaseYear, m.Genre, " +
                     "CONCAT(p.FirstName, ' ', p.LastName) AS DirectorName, m.Rating, m.ParentalRestriction " +
                     "FROM Movie m LEFT JOIN Person p ON m.DirectorId = p.PersonID " +
                     "WHERE (LOWER(m.Title) LIKE LOWER(?) " +
                     "OR LOWER(m.Genre) LIKE LOWER(?) " +
                     "OR CAST(m.ReleaseYear AS CHAR) LIKE ? " + 
                     "OR LOWER(p.FirstName) LIKE LOWER(?) " +
                     "OR LOWER(p.LastName) LIKE LOWER(?)) " +
                     "AND m.ParentalRestriction = FALSE"; 

        java.sql.PreparedStatement pst = conn.prepareStatement(sql);
        String searchPattern = "%" + key + "%";
        
        pst.setString(1, searchPattern);
        pst.setString(2, searchPattern);
        pst.setString(3, searchPattern);
        pst.setString(4, searchPattern);
        pst.setString(5, searchPattern);
        
        java.sql.ResultSet rs = pst.executeQuery();
        
        while(rs.next()) {
            Object[] row = {
                rs.getInt("MovieID"), 
                rs.getString("Title"), 
                rs.getInt("ReleaseYear"),
                rs.getString("Genre"), 
                rs.getString("DirectorName"),
                rs.getInt("Rating"), 
                rs.getBoolean("ParentalRestriction") ? "Restricted" : "Everyone"
            };
            model.addRow(row);
        }
        
        tblMovies.setModel(model);
        conn.close();
        
    } catch (Exception e) { 
        e.printStackTrace(); 
        javax.swing.JOptionPane.showMessageDialog(this, "Search Error: " + e.getMessage());
    }
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Type1MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Type1MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Type1MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Type1MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Type1MainFrame().setVisible(true);
            }
        });
    }

    public void updateMovieTable() {
   
    String[] columnNames = {"ID", "Title", "Year", "Genre", "Director", "Rating", "Restriction"};
    javax.swing.table.DefaultTableModel model = new javax.swing.table.DefaultTableModel(columnNames, 0) {
    @Override
    public boolean isCellEditable(int row, int column) {
        return false; 
    }
    };
    try {
    java.sql.Connection conn = DBConnection.getConnection();
   String sql = "SELECT m.MovieID, m.Title, m.ReleaseYear, m.Genre, " +
             "CONCAT(p.FirstName, ' ', p.LastName) AS DirectorFullName, " + 
             "m.Rating, m.ParentalRestriction " +
             "FROM Movie m " +
             "LEFT JOIN Person p ON m.DirectorId = p.PersonID";
    
    java.sql.Statement st = conn.createStatement();
    java.sql.ResultSet rs = st.executeQuery(sql);
    
    while(rs.next()) {
        Object[] row = {
            rs.getInt("MovieID"),
            rs.getString("Title"),
            rs.getInt("ReleaseYear"),
            rs.getString("Genre"),
            rs.getString("DirectorFullName"),
            rs.getInt("Rating"),
            rs.getBoolean("ParentalRestriction") ? "Restricted" : "Everyone"
        };
        model.addRow(row);
    }
    tblMovies.setModel(model); 
    conn.close();
}catch (Exception e) {
        javax.swing.JOptionPane.showMessageDialog(this, "Error loading movies: " + e.getMessage());
    }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAnalytics;
    private javax.swing.JButton btnConnect;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnManageUsers;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JButton btnToggleRestriction;
    private javax.swing.JButton btnViewRating;
    private javax.swing.Box.Filler filler1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblMovies;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables
}
