/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pkg2232_finalproject;



/**
 *
 * @author zeynepakhan
 */
public class Type2MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form Type1MainFrame
     */
    private String currentUserName;
    
    public Type2MainFrame(String userName) {
        initComponents();
        this.setResizable(false);
        this.currentUserName = userName; 
        updateMovieTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblMovies = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        txtSearch = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        btnViewRating = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblMovies.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblMovies);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 60, 783, 220));

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel3.setText("Search Movie:");
        jLabel3.setOpaque(true);
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 490, -1, -1));

        txtSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSearchActionPerformed(evt);
            }
        });
        txtSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSearchKeyReleased(evt);
            }
        });
        getContentPane().add(txtSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 490, 150, -1));

        jButton2.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        jButton2.setText("Browse");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 490, -1, -1));

        btnViewRating.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        btnViewRating.setText("View Family Rating");
        btnViewRating.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewRatingActionPerformed(evt);
            }
        });
        getContentPane().add(btnViewRating, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 320, -1, -1));

        jButton3.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        jButton3.setText("Mark Watched");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 320, -1, -1));

        jButton4.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        jButton4.setText("Rate/Comment");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 390, -1, -1));

        jButton5.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        jButton5.setText("Add to Watchlist");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 390, -1, -1));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Copperplate", 1, 24)); // NOI18N
        jLabel1.setText("CHILDREN Dashboard");
        jLabel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel1.setOpaque(true);
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 20, -1, -1));

        jButton6.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        jButton6.setText("Track Progress");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 320, -1, -1));

        btnLogout.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        btnLogout.setText("Logout");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });
        getContentPane().add(btnLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 490, -1, -1));

        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        jButton1.setText("Mark Unwatched");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 320, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pkg2232_finalproject/images/b99c237504dd5ae691d5587f30e3657a.png"))); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 820, 590));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtSearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchKeyReleased
      String searchKey = txtSearch.getText();
    updateMovieTableWithSearch(searchKey);
    }//GEN-LAST:event_txtSearchKeyReleased

    private void btnViewRatingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewRatingActionPerformed
        int selectedRow = tblMovies.getSelectedRow();
    if (selectedRow != -1) {
        int movieId = (int) tblMovies.getValueAt(selectedRow, 0);
        new RatingViewFrame(movieId).setVisible(true);
    } else {
        javax.swing.JOptionPane.showMessageDialog(this, "Select a movie first!");
    }
    }//GEN-LAST:event_btnViewRatingActionPerformed

    private void txtSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSearchActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        int selectedRow = tblMovies.getSelectedRow();
    if (selectedRow != -1) {
        int id = Integer.parseInt(tblMovies.getValueAt(selectedRow, 0).toString());
        
        MovieDetailsFrame df = new MovieDetailsFrame(id, 2); 
        df.setVisible(true);
    } else {
        javax.swing.JOptionPane.showMessageDialog(this, "Please select a movie!");
    }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
       int selectedRow = tblMovies.getSelectedRow();
    if (selectedRow != -1) {
        int movieId = Integer.parseInt(tblMovies.getValueAt(selectedRow, 0).toString());
        try {
            java.sql.Connection conn = DBConnection.getConnection();
           
            String sql = "UPDATE Movie SET Watched = TRUE WHERE MovieID = ?";
            java.sql.PreparedStatement pst = conn.prepareStatement(sql);
            pst.setInt(1, movieId);
            pst.executeUpdate();
            
            javax.swing.JOptionPane.showMessageDialog(this, "Movie marked as watched! Great job!");
            updateMovieTable(); 
            conn.close();
        } catch (Exception e) { e.printStackTrace(); }
    } else {
        javax.swing.JOptionPane.showMessageDialog(this, "Please select a movie first!");
    }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
       int selectedRow = tblMovies.getSelectedRow();
    if (selectedRow != -1) {
        int movieId = Integer.parseInt(tblMovies.getValueAt(selectedRow, 0).toString());
        
        String ratingStr = javax.swing.JOptionPane.showInputDialog(this, "Enter your rating (1-10):");
        if (ratingStr == null) return; 

        try {
            int rating = Integer.parseInt(ratingStr);
            if (rating < 1 || rating > 10) {
                javax.swing.JOptionPane.showMessageDialog(this, "Please enter a rating between 1 and 10!");
                return;
            }

            String comment = javax.swing.JOptionPane.showInputDialog(this, "Write a short comment:");
            if (comment == null) return;

            java.sql.Connection conn = DBConnection.getConnection();
           
            String sql = "INSERT INTO UserComments (MovieID, UserName, UserRating, UserComment) VALUES (?, ?, ?, ?) " +
                         "ON DUPLICATE KEY UPDATE UserRating = ?, UserComment = ?";
            
            java.sql.PreparedStatement pst = conn.prepareStatement(sql);
            pst.setInt(1, movieId);
            pst.setString(2, currentUserName);
            pst.setInt(3, rating);
            pst.setString(4, comment);
            pst.setInt(5, rating);
            pst.setString(6, comment);
            
            pst.executeUpdate();
            javax.swing.JOptionPane.showMessageDialog(this, "Thank you for your review!");
            conn.close();
        } catch (NumberFormatException e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Invalid input! Please enter a numeric value for rating.");
        } catch (Exception e) {
            e.printStackTrace();
        }
    } else {
        javax.swing.JOptionPane.showMessageDialog(this, "Please select a movie first!");
    }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
                                               
    int selectedRow = tblMovies.getSelectedRow();
    if (selectedRow != -1) {
       
        int movieId = Integer.parseInt(tblMovies.getValueAt(selectedRow, 0).toString());
        
        try {
            java.sql.Connection conn = DBConnection.getConnection();
            
            String sql = "INSERT IGNORE INTO Watchlist (UserName, MovieID) VALUES (?, ?)";
            java.sql.PreparedStatement pst = conn.prepareStatement(sql);
            
            pst.setString(1, currentUserName);
            pst.setInt(2, movieId);
            
            int result = pst.executeUpdate();
            
            if (result > 0) {
                javax.swing.JOptionPane.showMessageDialog(this, "Success! Movie added to your watchlist.");
            } else {
                javax.swing.JOptionPane.showMessageDialog(this, "This movie is already in your watchlist!");
            }
            
            conn.close();
        } catch (Exception e) { 
            
            e.printStackTrace(); 
            javax.swing.JOptionPane.showMessageDialog(this, "DB Error: " + e.getMessage());
        }
    } else {
        javax.swing.JOptionPane.showMessageDialog(this, "Please select a movie first!");
    }

    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
       try {
        java.sql.Connection conn = DBConnection.getConnection();
        
        String sql = "SELECT UserName, COUNT(*) as Total FROM UserComments GROUP BY UserName";
        java.sql.Statement st = conn.createStatement();
        java.sql.ResultSet rs = st.executeQuery(sql);
        
        StringBuilder report = new StringBuilder("--- Family Progress ---\n");
        while (rs.next()) {
            report.append(rs.getString("UserName")).append(": ")
                  .append(rs.getInt("Total")).append(" movies watched.\n");
        }
        
        javax.swing.JOptionPane.showMessageDialog(this, report.toString());
        conn.close();
    } catch (Exception e) { e.printStackTrace(); }

    }//GEN-LAST:event_jButton6ActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        this.dispose(); 
    
    new LoginFrame().setVisible(true);
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int selectedRow = tblMovies.getSelectedRow();
    if (selectedRow != -1) {
       
        int movieId = Integer.parseInt(tblMovies.getValueAt(selectedRow, 0).toString());
        
        try {
            java.sql.Connection conn = DBConnection.getConnection();
           
            String sql = "UPDATE Movie SET Watched = FALSE WHERE MovieID = ?";
            java.sql.PreparedStatement pst = conn.prepareStatement(sql);
            pst.setInt(1, movieId);
            
            pst.executeUpdate();
            javax.swing.JOptionPane.showMessageDialog(this, "Movie marked as Not Watched!");
            
            updateMovieTable(); 
            conn.close();
        } catch (Exception e) {
            e.printStackTrace();
        }
    } else {
        javax.swing.JOptionPane.showMessageDialog(this, "Select a movie first!");
    }
    }//GEN-LAST:event_jButton1ActionPerformed

    
    public void updateMovieTableWithSearch(String key) {
    String[] columnNames = {"ID", "Title", "Year", "Genre", "Director", "Rating", "Restriction"};
    javax.swing.table.DefaultTableModel model = new javax.swing.table.DefaultTableModel(columnNames, 0);
    
    try {
        java.sql.Connection conn = DBConnection.getConnection();
    
        String sql = "SELECT m.MovieID, m.Title, m.ReleaseYear, m.Genre, " +
                     "CONCAT(p.FirstName, ' ', p.LastName) AS DirectorName, m.Rating, m.ParentalRestriction " +
                     "FROM Movie m LEFT JOIN Person p ON m.DirectorId = p.PersonID " +
                     "WHERE (LOWER(m.Title) LIKE LOWER(?) " +
                     "OR LOWER(m.Genre) LIKE LOWER(?) " +
                     "OR CAST(m.ReleaseYear AS CHAR) LIKE ? " + 
                     "OR LOWER(p.FirstName) LIKE LOWER(?) " +
                     "OR LOWER(p.LastName) LIKE LOWER(?)) " +
                     "AND m.ParentalRestriction = FALSE"; 

        java.sql.PreparedStatement pst = conn.prepareStatement(sql);
        String searchPattern = "%" + key + "%";
        
        pst.setString(1, searchPattern);
        pst.setString(2, searchPattern);
        pst.setString(3, searchPattern);
        pst.setString(4, searchPattern);
        pst.setString(5, searchPattern);
        
        java.sql.ResultSet rs = pst.executeQuery();
        
        while(rs.next()) {
            Object[] row = {
                rs.getInt("MovieID"), 
                rs.getString("Title"), 
                rs.getInt("ReleaseYear"),
                rs.getString("Genre"), 
                rs.getString("DirectorName"),
                rs.getInt("Rating"), 
                rs.getBoolean("ParentalRestriction") ? "Restricted" : "Everyone"
            };
            model.addRow(row);
        }
        
        tblMovies.setModel(model);
        conn.close();
        
    } catch (Exception e) { 
        e.printStackTrace(); 
        javax.swing.JOptionPane.showMessageDialog(this, "Search Error: " + e.getMessage());
    }
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Type2MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Type2MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Type2MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Type2MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Type2MainFrame("TestUser").setVisible(true);
            }
        });
    }

    public void updateMovieTable() {
   
    String[] columnNames = {"ID", "Title", "Year", "Genre", "Director", "Rating", "Restriction"};
    javax.swing.table.DefaultTableModel model = new javax.swing.table.DefaultTableModel(columnNames, 0) {
    @Override
    public boolean isCellEditable(int row, int column) {
        return false; 
    }
    };
    try {
    java.sql.Connection conn = DBConnection.getConnection();
   String sql = "SELECT m.MovieID, m.Title, m.ReleaseYear, m.Genre, " +
                 "CONCAT(p.FirstName, ' ', p.LastName) AS DirectorFullName, " + 
                 "m.Rating, m.ParentalRestriction " +
                 "FROM Movie m " +
                 "LEFT JOIN Person p ON m.DirectorId = p.PersonID " +
                 "WHERE m.ParentalRestriction = FALSE";
    
    java.sql.Statement st = conn.createStatement();
    java.sql.ResultSet rs = st.executeQuery(sql);
    
    while(rs.next()) {
        Object[] row = {
            rs.getInt("MovieID"),
            rs.getString("Title"),
            rs.getInt("ReleaseYear"),
            rs.getString("Genre"),
            rs.getString("DirectorFullName"),
            rs.getInt("Rating"),
            rs.getBoolean("ParentalRestriction") ? "Restricted" : "Everyone"
        };
        model.addRow(row);
    }
    if (model.getRowCount() == 0) {
    javax.swing.JOptionPane.showMessageDialog(this, "No movies available for children right now!");
}
    tblMovies.setModel(model); 
    conn.close();
}catch (Exception e) {
        javax.swing.JOptionPane.showMessageDialog(this, "Error loading movies: " + e.getMessage());
    }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnViewRating;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblMovies;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables
}
