/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pkg2232_finalproject;
import java.io.File;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author zeynepakhan
 */
public class AddMovieFrame extends javax.swing.JFrame {

    /**
     * Creates new form AddMovieFrame
     */
   
    private int mid=-1;
    private String currentPosterPath = "";
    public AddMovieFrame() {
        initComponents();
        setNextID();
        this.setResizable(false);
        btnSave.setText("Save");
        jButton1.setEnabled(true);
    }
    public AddMovieFrame(int movieId) {
    initComponents();
        this.mid = movieId;
        this.setResizable(false);
        btnSave.setText("Update");
        jButton1.setEnabled(false); 
        loadMovieData();
}
    
   
public void setNextID() {
    try {
            java.sql.Connection conn = DBConnection.getConnection();
            String sql = "SELECT MAX(MovieID) FROM Movie";
            java.sql.PreparedStatement pst = conn.prepareStatement(sql);
            java.sql.ResultSet rs = pst.executeQuery();

            if (rs.next()) {
                int maxId = rs.getInt(1);
                txtID.setText(String.valueOf(maxId + 1));
            } else {
                txtID.setText("1");
            }
            conn.close();
        } catch (Exception e) {
            e.printStackTrace();
        }
}
    private void loadMovieData() {
    try {
            java.sql.Connection conn = DBConnection.getConnection();

            String sql = "SELECT m.*, p.FirstName, p.LastName FROM Movie m "
                    + "LEFT JOIN Person p ON m.DirectorId = p.PersonID "
                    + "WHERE m.MovieID = ?";
            java.sql.PreparedStatement pst = conn.prepareStatement(sql);
            pst.setInt(1, mid);
            java.sql.ResultSet rs = pst.executeQuery();

            if (rs.next()) {
                txtID.setText(String.valueOf(rs.getInt("MovieID")));
                txtTitle.setText(rs.getString("Title"));
                txtYear.setText(String.valueOf(rs.getInt("ReleaseYear")));
                txtGenre.setText(rs.getString("Genre"));
                txtAbout.setText(rs.getString("About"));
                
                currentPosterPath = rs.getString("Poster");
                lblPosterPath.setText(currentPosterPath);

                String fName = rs.getString("FirstName") == null ? "" : rs.getString("FirstName");
                String lName = rs.getString("LastName") == null ? "" : rs.getString("LastName");
                txtDirectorName.setText((fName + " " + lName).trim());

                cmbRating.setSelectedItem(String.valueOf(rs.getInt("Rating")));
                chbRestricted.setSelected(rs.getBoolean("ParentalRestriction"));
            }
            conn.close();
        } catch (Exception e) {
            e.printStackTrace();
        }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtID = new javax.swing.JTextField();
        txtTitle = new javax.swing.JTextField();
        txtYear = new javax.swing.JTextField();
        btnSave = new javax.swing.JButton();
        txtGenre = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAbout = new javax.swing.JTextArea();
        chbRestricted = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cmbRating = new javax.swing.JComboBox<>();
        txtDirectorName = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        lblPosterPath = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtID.setEditable(false);
        getContentPane().add(txtID, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 80, 130, -1));

        txtTitle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTitleActionPerformed(evt);
            }
        });
        getContentPane().add(txtTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 160, 130, -1));

        txtYear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtYearActionPerformed(evt);
            }
        });
        getContentPane().add(txtYear, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 240, 130, -1));

        btnSave.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        getContentPane().add(btnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 520, -1, -1));
        getContentPane().add(txtGenre, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 240, 130, -1));

        txtAbout.setColumns(20);
        txtAbout.setRows(5);
        jScrollPane1.setViewportView(txtAbout);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 330, 210, -1));

        chbRestricted.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        chbRestricted.setText("Restriction");
        chbRestricted.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chbRestrictedActionPerformed(evt);
            }
        });
        getContentPane().add(chbRestricted, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 470, 128, -1));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setText("ID:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, 44, -1));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel2.setText("Title:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, -1, 23));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel3.setText("Year:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 240, -1, -1));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel4.setText("Genre:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 240, -1, -1));

        cmbRating.setFont(new java.awt.Font("Times New Roman", 0, 15)); // NOI18N
        cmbRating.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));
        getContentPane().add(cmbRating, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 150, -1, -1));
        getContentPane().add(txtDirectorName, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 80, 130, -1));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel5.setText("About:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 360, -1, -1));

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel8.setText("Director:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 80, -1, -1));

        jLabel10.setFont(new java.awt.Font("Copperplate", 1, 24)); // NOI18N
        jLabel10.setText("ADD/UPDATE MOVIE");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 10, -1, -1));

        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton1.setText("Select Poster");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 320, -1, -1));

        lblPosterPath.setFont(new java.awt.Font("Times New Roman", 3, 13)); // NOI18N
        getContentPane().add(lblPosterPath, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 360, 230, 20));

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel9.setText("Rating:");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 160, -1, -1));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pkg2232_finalproject/images/c4f030132cc9da7fcd537d4d722e5d07.png"))); // NOI18N
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 690, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pkg2232_finalproject/images/c4f030132cc9da7fcd537d4d722e5d07 kopyası.png"))); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 690, 160));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
      String movieTitle = txtTitle.getText();
        String directorFullName = txtDirectorName.getText().trim();
        int rating = Integer.parseInt(cmbRating.getSelectedItem().toString());
        int directorId = -1;

        if (directorFullName.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Please enter a Director name!");
            return;
        }

        try {
            java.sql.Connection conn = DBConnection.getConnection();

            String[] nameParts = directorFullName.split(" ", 2);
            String fName = nameParts[0];
            String lName = (nameParts.length > 1) ? nameParts[1] : "";

            String checkPersonSql = "SELECT PersonID FROM Person WHERE UPPER(FirstName) = UPPER(?) AND UPPER(LastName) = UPPER(?)";
            java.sql.PreparedStatement pstCheck = conn.prepareStatement(checkPersonSql);
            pstCheck.setString(1, fName);
            pstCheck.setString(2, lName);
            java.sql.ResultSet rs = pstCheck.executeQuery();

            if (rs.next()) {
                directorId = rs.getInt("PersonID");
            } else {
                java.sql.Statement stMax = conn.createStatement();
                java.sql.ResultSet rsMax = stMax.executeQuery("SELECT MAX(PersonID) FROM Person");
                int maxPersonId = (rsMax.next()) ? rsMax.getInt(1) : 0;
                directorId = maxPersonId + 1;

                String insertPersonSql = "INSERT INTO Person (PersonID, FirstName, LastName) VALUES (?, ?, ?)";
                java.sql.PreparedStatement pstPerson = conn.prepareStatement(insertPersonSql);
                pstPerson.setInt(1, directorId);
                pstPerson.setString(2, fName);
                pstPerson.setString(3, lName);
                pstPerson.executeUpdate();
            }

       
            String sql;
            if (mid == -1) {
             
                sql = "INSERT INTO Movie (MovieID, Title, ReleaseYear, Genre, About, ParentalRestriction, DirectorId, Rating, Poster) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)";
            } else {
             
                sql = "UPDATE Movie SET MovieID=?, Title=?, ReleaseYear=?, Genre=?, About=?, ParentalRestriction=?, DirectorId=?, Rating=?, Poster=? WHERE MovieID = ?";
            }

            java.sql.PreparedStatement pst = conn.prepareStatement(sql);
            pst.setInt(1, Integer.parseInt(txtID.getText()));
            pst.setString(2, movieTitle);
            pst.setInt(3, Integer.parseInt(txtYear.getText()));
            pst.setString(4, txtGenre.getText());
            pst.setString(5, txtAbout.getText());
            pst.setBoolean(6, chbRestricted.isSelected());
            pst.setInt(7, directorId);
            pst.setInt(8, rating);
            pst.setString(9, currentPosterPath); 

            if (mid != -1) {
                pst.setInt(10, mid);
            }

            pst.executeUpdate();

            String msg = (mid == -1) ? "Movie saved with poster!" : "Movie updated!";
            javax.swing.JOptionPane.showMessageDialog(this, msg);

            this.dispose();
            conn.close();

        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
            e.printStackTrace();
        }
                            
    
    }//GEN-LAST:event_btnSaveActionPerformed

    private void chbRestrictedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chbRestrictedActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chbRestrictedActionPerformed

    private void txtYearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtYearActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtYearActionPerformed

    private void txtTitleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTitleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTitleActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        JFileChooser fileChooser = new JFileChooser();
        FileNameExtensionFilter filter = new FileNameExtensionFilter("Image Files", "jpg", "png", "jpeg");
        fileChooser.setFileFilter(filter);

        int result = fileChooser.showOpenDialog(this);
        if (result == JFileChooser.APPROVE_OPTION) {
            File selectedFile = fileChooser.getSelectedFile();
           
            currentPosterPath = "src/pkg2232_finalproject/posters/" + selectedFile.getName();
            lblPosterPath.setText(selectedFile.getName()); 
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddMovieFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddMovieFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddMovieFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddMovieFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddMovieFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSave;
    private javax.swing.JCheckBox chbRestricted;
    private javax.swing.JComboBox<String> cmbRating;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblPosterPath;
    private javax.swing.JTextArea txtAbout;
    private javax.swing.JTextField txtDirectorName;
    private javax.swing.JTextField txtGenre;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtTitle;
    private javax.swing.JTextField txtYear;
    // End of variables declaration//GEN-END:variables
}
